# Generated by Django 3.2 on 2021-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210506_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['due_date', '-status']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-05-07'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-05-07'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
